apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-app
  template:
    metadata:
      labels:
        app: status-app
    spec:
      initContainers:
      - name: permissions-fix
        image: busybox
        command: ["sh", "-c", "chmod -R 755 /usr/share/nginx/html"]
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        hostPath:
          path: /local-src/status-app
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: status-app-service
spec:
  selector:
    app: status-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: status-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: status.${LOCAL_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: status-app-service
            port:
              number: 80
  tls:
  - hosts:
    - status.${LOCAL_DOMAIN}
    secretName: local-dev-tls 